/**
 * 关卡配置数据
 *
 * 【注意】本文件由关卡编辑器生成，已覆盖原有手写关卡。
 * 生成时间：2026/9/6 18:14:46
 */

import { ItemType, LevelConfig } from '../types/index';

export const LEVELS: LevelConfig[] = [
  // 第 1 关
  {
    level: 1,
    grid: { rows: 5, cols: 5 },
    obstacles: [
      [1, 0],
      [1, 1],
      [1, 2],
      [4, 0],
      [4, 1],
      [4, 2],
      [4, 3],
      [2, 0],
      [2, 2],
      [2, 1],
      [0, 2],
      [0, 1],
      [0, 0],
      [4, 4],
      [3, 4],
      [2, 4],
      [1, 4],
    ],
    items: [
      { type: ItemType.MUG_RED, pos: [3, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.MUG_RED, pos: [0, 4] },
    ],
  },

  // 第 2 关
  {
    level: 2,
    grid: { rows: 5, cols: 5 },
    obstacles: [
      [1, 1],
      [1, 3],
      [2, 0],
      [2, 1],
      [2, 2],
      [2, 3],
      [4, 2],
      [4, 3],
      [4, 4],
      [4, 1],
      [1, 0],
    ],
    items: [
      { type: ItemType.BOOK_BLUE, pos: [3, 0], layer: 1 },
      { type: ItemType.MUG_RED, pos: [0, 2], layer: 1 },
    ],
    targets: [
      { type: ItemType.BOOK_BLUE, pos: [0, 1] },
      { type: ItemType.MUG_RED, pos: [4, 0] },
    ],
    maxSteps: 99,
  },

  // 第 3 关
  {
    level: 3,
    grid: { rows: 5, cols: 4 },
    obstacles: [
      [2, 0],
      [2, 1],
      [2, 2],
      [1, 1],
      [1, 0],
      [1, 2],
    ],
    items: [
      { type: ItemType.MUG_RED, pos: [0, 0], layer: 2 },
      { type: ItemType.SHOE_YELLOW, pos: [0, 0], layer: 1 },
      { type: ItemType.SHOE_YELLOW, pos: [3, 3], layer: 3 },
      { type: ItemType.HAT_PURPLE, pos: [3, 3], layer: 1 },
      { type: ItemType.BOOK_BLUE, pos: [3, 3], layer: 2 },
    ],
    targets: [
      { type: ItemType.MUG_RED, pos: [4, 0] },
      { type: ItemType.BOOK_BLUE, pos: [4, 3] },
      { type: ItemType.SHOE_YELLOW, pos: [1, 3] },
      { type: ItemType.HAT_PURPLE, pos: [3, 0] },
    ],
    maxSteps: 99,
  },

  // 第 4 关
  {
    level: 4,
    grid: { rows: 6, cols: 5 },
    obstacles: [
      [2, 3],
      [2, 2],
      [2, 1],
      [2, 4],
      [3, 1],
      [0, 4],
      [0, 3],
      [0, 2],
      [0, 1],
    ],
    items: [
      { type: ItemType.APPLE_GREEN, pos: [1, 4], layer: 2 },
      { type: ItemType.HEADPHONE_BLACK, pos: [4, 0], layer: 3 },
      { type: ItemType.ALARM_PINK, pos: [1, 4], layer: 1 },
      { type: ItemType.BOOK_BLUE, pos: [4, 0], layer: 2 },
      { type: ItemType.ALARM_PINK, pos: [1, 0], layer: 1 },
      { type: ItemType.SHOE_YELLOW, pos: [4, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.APPLE_GREEN, pos: [4, 0] },
      { type: ItemType.HEADPHONE_BLACK, pos: [1, 4] },
      { type: ItemType.ALARM_PINK, pos: [4, 4] },
      { type: ItemType.BOOK_BLUE, pos: [1, 3] },
      { type: ItemType.SHOE_YELLOW, pos: [5, 0] },
    ],
    maxSteps: 30,
  },

  // 第 5 关
  {
    level: 5,
    grid: { rows: 7, cols: 5 },
    obstacles: [
      [1, 1],
      [4, 1],
      [1, 3],
      [4, 3],
      [2, 1],
      [2, 3],
      [5, 1],
      [5, 3],
      [3, 2],
    ],
    items: [
      { type: ItemType.MUG_RED, pos: [0, 0], layer: 3 },
      { type: ItemType.PLANT_GREEN, pos: [0, 0], layer: 2 },
      { type: ItemType.BOOK_BLUE, pos: [0, 0], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [0, 2], layer: 2 },
      { type: ItemType.ALARM_PINK, pos: [3, 0], layer: 2 },
      { type: ItemType.ALARM_PINK, pos: [0, 2], layer: 1 },
      { type: ItemType.PLANT_GREEN, pos: [6, 2], layer: 1 },
      { type: ItemType.MUG_RED, pos: [2, 2], layer: 1 },
      { type: ItemType.BOOK_BLUE, pos: [3, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.PLANT_GREEN, pos: [0, 4] },
      { type: ItemType.BOOK_BLUE, pos: [6, 0] },
      { type: ItemType.LAMP_ORANGE, pos: [6, 2] },
      { type: ItemType.MUG_RED, pos: [6, 4] },
      { type: ItemType.ALARM_PINK, pos: [3, 4] },
    ],
    maxSteps: 30,
  },

  // 第 6 关
  {
    level: 6,
    grid: { rows: 7, cols: 5 },
    obstacles: [
      [1, 0],
      [2, 0],
      [3, 0],
      [0, 2],
      [2, 2],
      [3, 2],
      [4, 2],
      [6, 2],
      [5, 4],
      [4, 4],
      [3, 4],
    ],
    items: [
      { type: ItemType.ALARM_PINK, pos: [0, 4], layer: 2 },
      { type: ItemType.LAMP_ORANGE, pos: [0, 4], layer: 1 },
      { type: ItemType.ALARM_PINK, pos: [1, 2], layer: 3 },
      { type: ItemType.HEADPHONE_BLACK, pos: [1, 2], layer: 2 },
      { type: ItemType.HAT_PURPLE, pos: [1, 2], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [5, 3], layer: 1 },
      { type: ItemType.HEADPHONE_BLACK, pos: [5, 1], layer: 1 },
    ],
    targets: [
      { type: ItemType.ALARM_PINK, pos: [6, 0] },
      { type: ItemType.LAMP_ORANGE, pos: [0, 0] },
      { type: ItemType.HEADPHONE_BLACK, pos: [6, 4] },
      { type: ItemType.HAT_PURPLE, pos: [5, 2] },
    ],
    maxSteps: 30,
  },

  // 第 7 关
  {
    level: 7,
    grid: { rows: 7, cols: 5 },
    obstacles: [
      [1, 0],
      [2, 0],
      [5, 0],
      [6, 0],
      [4, 2],
      [3, 2],
      [2, 2],
      [1, 2],
      [5, 2],
      [1, 4],
      [2, 4],
      [5, 4],
      [6, 4],
    ],
    items: [
      { type: ItemType.HEADPHONE_BLACK, pos: [4, 4], layer: 2 },
      { type: ItemType.ALARM_PINK, pos: [4, 4], layer: 1 },
      { type: ItemType.MUG_RED, pos: [0, 0], layer: 3 },
      { type: ItemType.LAMP_ORANGE, pos: [4, 3], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [0, 4], layer: 2 },
      { type: ItemType.MUG_RED, pos: [0, 4], layer: 1 },
      { type: ItemType.SHOE_YELLOW, pos: [0, 0], layer: 2 },
      { type: ItemType.HAT_PURPLE, pos: [0, 1], layer: 2 },
      { type: ItemType.LAMP_ORANGE, pos: [0, 0], layer: 1 },
      { type: ItemType.HEADPHONE_BLACK, pos: [0, 1], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [6, 1], layer: 1 },
    ],
    targets: [
      { type: ItemType.MUG_RED, pos: [4, 4] },
      { type: ItemType.ALARM_PINK, pos: [0, 0] },
      { type: ItemType.LAMP_ORANGE, pos: [0, 4] },
      { type: ItemType.SHOE_YELLOW, pos: [0, 1] },
      { type: ItemType.HAT_PURPLE, pos: [3, 0] },
      { type: ItemType.HEADPHONE_BLACK, pos: [6, 3] },
    ],
    maxSteps: 40,
  },

  // 第 8 关
  {
    level: 8,
    grid: { rows: 7, cols: 6 },
    obstacles: [
      [4, 1],
      [3, 1],
      [2, 1],
      [1, 1],
      [1, 2],
      [0, 4],
      [1, 4],
      [2, 4],
      [3, 4],
      [3, 3],
      [4, 3],
      [5, 3],
      [6, 2],
      [2, 3],
    ],
    portals: [
      { id: 1, pos: [1, 3], uses: 3 },
      { id: 1, pos: [3, 5], uses: 3 },
    ],
    items: [
      { type: ItemType.APPLE_GREEN, pos: [4, 0], layer: 3 },
      { type: ItemType.APPLE_GREEN, pos: [4, 0], layer: 2 },
      { type: ItemType.APPLE_GREEN, pos: [4, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.APPLE_GREEN, pos: [4, 5] },
    ],
    maxSteps: 15,
  },

  // 第 9 关
  {
    level: 9,
    grid: { rows: 7, cols: 6 },
    obstacles: [
      [4, 0],
      [4, 1],
      [4, 2],
      [4, 3],
      [4, 4],
      [4, 5],
      [2, 0],
      [2, 1],
      [2, 2],
      [2, 3],
      [2, 4],
      [2, 5],
    ],
    portals: [
      { id: 1, pos: [1, 0], uses: 1 },
      { id: 1, pos: [5, 0], uses: 1 },
      { id: 2, pos: [1, 2], uses: 1 },
      { id: 2, pos: [5, 2], uses: 1 },
      { id: 3, pos: [1, 4], uses: 5 },
      { id: 3, pos: [5, 4], uses: 5 },
    ],
    items: [
      { type: ItemType.MUG_RED, pos: [0, 0], layer: 1 },
      { type: ItemType.BOOK_BLUE, pos: [0, 1], layer: 1 },
      { type: ItemType.PLANT_GREEN, pos: [0, 3], layer: 1 },
      { type: ItemType.SHOE_YELLOW, pos: [0, 4], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [0, 2], layer: 1 },
      { type: ItemType.HEADPHONE_BLACK, pos: [0, 5], layer: 1 },
    ],
    targets: [
      { type: ItemType.MUG_RED, pos: [6, 0] },
      { type: ItemType.BOOK_BLUE, pos: [6, 1] },
      { type: ItemType.HAT_PURPLE, pos: [6, 2] },
      { type: ItemType.PLANT_GREEN, pos: [6, 3] },
      { type: ItemType.SHOE_YELLOW, pos: [6, 4] },
      { type: ItemType.HEADPHONE_BLACK, pos: [6, 5] },
    ],
    maxSteps: 15,
    maxRefreshes: 4,
  },

  // 第 10 关
  {
    level: 10,
    grid: { rows: 7, cols: 6 },
    obstacles: [
      [2, 2],
      [5, 0],
      [5, 1],
      [5, 2],
      [2, 1],
      [1, 1],
      [3, 1],
      [4, 1],
      [5, 3],
      [6, 3],
      [1, 0],
      [6, 5],
      [5, 5],
    ],
    portals: [
      { id: 1, pos: [0, 1], uses: 4 },
      { id: 1, pos: [6, 2], uses: 4 },
      { id: 2, pos: [6, 4], uses: 2 },
      { id: 2, pos: [2, 0], uses: 2 },
    ],
    items: [
      { type: ItemType.MUG_RED, pos: [0, 2], layer: 2 },
      { type: ItemType.BOOK_BLUE, pos: [6, 0], layer: 2 },
      { type: ItemType.PLANT_GREEN, pos: [1, 2], layer: 2 },
      { type: ItemType.PLANT_GREEN, pos: [0, 3], layer: 2 },
      { type: ItemType.APPLE_GREEN, pos: [5, 4], layer: 3 },
      { type: ItemType.BOOK_BLUE, pos: [5, 4], layer: 2 },
      { type: ItemType.MUG_RED, pos: [5, 4], layer: 1 },
      { type: ItemType.MUG_RED, pos: [1, 2], layer: 1 },
      { type: ItemType.MUG_RED, pos: [0, 3], layer: 1 },
      { type: ItemType.MUG_RED, pos: [0, 2], layer: 1 },
      { type: ItemType.MUG_RED, pos: [6, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.BOOK_BLUE, pos: [4, 0] },
      { type: ItemType.MUG_RED, pos: [0, 5] },
      { type: ItemType.PLANT_GREEN, pos: [6, 0] },
      { type: ItemType.APPLE_GREEN, pos: [3, 5] },
    ],
    maxSteps: 30,
  },

  // 第 11 关
  {
    level: 11,
    grid: { rows: 8, cols: 6 },
    obstacles: [
      [1, 1],
      [3, 1],
      [5, 1],
      [7, 1],
      [0, 3],
      [2, 3],
      [4, 3],
      [6, 3],
      [1, 5],
      [3, 5],
      [5, 5],
      [7, 5],
      [6, 2],
      [3, 4],
    ],
    portals: [
      { id: 1, pos: [0, 2], uses: 2 },
      { id: 1, pos: [4, 4], uses: 2 },
    ],
    items: [
      { type: ItemType.APPLE_GREEN, pos: [0, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.APPLE_GREEN, pos: [7, 4] },
    ],
    maxSteps: 5,
  },

  // 第 12 关
  {
    level: 12,
    grid: { rows: 8, cols: 6 },
    obstacles: [
      [2, 2],
      [5, 2],
      [6, 2],
      [7, 2],
      [5, 3],
      [5, 5],
      [5, 4],
      [2, 3],
      [2, 5],
      [2, 4],
      [5, 0],
      [5, 1],
      [2, 1],
      [2, 0],
      [0, 3],
      [1, 3],
    ],
    portals: [
      { id: 3, pos: [1, 5], uses: 2 },
      { id: 3, pos: [6, 5], uses: 2 },
      { id: 4, pos: [0, 2], uses: 3 },
      { id: 4, pos: [4, 1], uses: 3 },
      { id: 5, pos: [7, 3], uses: 3 },
      { id: 5, pos: [3, 3], uses: 3 },
    ],
    items: [
      { type: ItemType.LAMP_ORANGE, pos: [1, 0], layer: 2 },
      { type: ItemType.HEADPHONE_BLACK, pos: [1, 0], layer: 3 },
      { type: ItemType.APPLE_GREEN, pos: [1, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.HEADPHONE_BLACK, pos: [0, 5] },
      { type: ItemType.LAMP_ORANGE, pos: [0, 4] },
      { type: ItemType.APPLE_GREEN, pos: [4, 5] },
    ],
    maxSteps: 20,
  },

  // 第 13 关
  {
    level: 13,
    grid: { rows: 9, cols: 6 },
    obstacles: [
      [0, 3],
      [2, 3],
      [6, 3],
      [7, 3],
      [8, 3],
      [6, 4],
      [6, 5],
      [6, 2],
      [6, 1],
      [6, 0],
      [3, 3],
      [4, 3],
    ],
    portals: [
      { id: 1, pos: [7, 4], uses: 15 },
      { id: 1, pos: [1, 4], uses: 15 },
      { id: 2, pos: [0, 2], uses: 3 },
      { id: 2, pos: [8, 1], uses: 3 },
    ],
    items: [
      { type: ItemType.APPLE_GREEN, pos: [8, 5], layer: 3 },
      { type: ItemType.ALARM_PINK, pos: [8, 5], layer: 2 },
      { type: ItemType.PLANT_GREEN, pos: [8, 5], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [7, 5], layer: 3 },
      { type: ItemType.SHOE_YELLOW, pos: [7, 5], layer: 2 },
      { type: ItemType.MUG_RED, pos: [7, 5], layer: 1 },
      { type: ItemType.PLANT_GREEN, pos: [0, 0], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [0, 0], layer: 2 },
      { type: ItemType.HAT_PURPLE, pos: [0, 0], layer: 3 },
      { type: ItemType.APPLE_GREEN, pos: [8, 4], layer: 1 },
      { type: ItemType.SHOE_YELLOW, pos: [8, 4], layer: 2 },
    ],
    targets: [
      { type: ItemType.PLANT_GREEN, pos: [0, 0] },
      { type: ItemType.APPLE_GREEN, pos: [0, 5] },
      { type: ItemType.ALARM_PINK, pos: [5, 5] },
      { type: ItemType.LAMP_ORANGE, pos: [5, 0] },
      { type: ItemType.SHOE_YELLOW, pos: [8, 0] },
      { type: ItemType.MUG_RED, pos: [8, 2] },
      { type: ItemType.HAT_PURPLE, pos: [8, 4] },
    ],
    maxSteps: 50,
  },

  // 第 14 关
  {
    level: 14,
    grid: { rows: 8, cols: 6 },
    obstacles: [
      [1, 1],
      [1, 0],
      [1, 2],
      [2, 3],
      [3, 3],
      [4, 3],
      [4, 4],
      [4, 5],
      [3, 5],
      [2, 5],
      [1, 5],
      [3, 1],
      [4, 1],
      [2, 0],
      [2, 1],
      [6, 1],
    ],
    portals: [
      { id: 1, pos: [3, 4], uses: 5 },
      { id: 1, pos: [3, 0], uses: 5 },
    ],
    waters: [
      { pos: [0, 4], freezeIn: 1 },
      { pos: [6, 0], freezeIn: 6 },
    ],
    items: [
      { type: ItemType.MUG_RED, pos: [0, 0], layer: 3 },
      { type: ItemType.BOOK_BLUE, pos: [0, 0], layer: 2 },
      { type: ItemType.PLANT_GREEN, pos: [0, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.PLANT_GREEN, pos: [0, 5] },
      { type: ItemType.BOOK_BLUE, pos: [7, 0] },
      { type: ItemType.MUG_RED, pos: [5, 5] },
    ],
    maxSteps: 16,
  },

  // 第 15 关
  {
    level: 15,
    grid: { rows: 8, cols: 6 },
    obstacles: [
      [3, 1],
      [3, 5],
      [3, 4],
      [4, 1],
      [1, 1],
      [2, 1],
      [3, 3],
      [1, 3],
      [1, 4],
      [1, 5],
      [6, 1],
      [6, 2],
      [6, 3],
      [6, 4],
    ],
    waters: [
      { pos: [4, 0], freezeIn: 5 },
      { pos: [4, 2], freezeIn: 3 },
    ],
    items: [
      { type: ItemType.SHOE_YELLOW, pos: [0, 0], layer: 3 },
      { type: ItemType.HAT_PURPLE, pos: [0, 0], layer: 2 },
      { type: ItemType.LAMP_ORANGE, pos: [0, 0], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [0, 2], layer: 1 },
    ],
    targets: [
      { type: ItemType.LAMP_ORANGE, pos: [4, 5] },
      { type: ItemType.SHOE_YELLOW, pos: [4, 4] },
      { type: ItemType.HAT_PURPLE, pos: [7, 5] },
    ],
    maxSteps: 15,
  },

  // 第 16 关
  {
    level: 16,
    grid: { rows: 8, cols: 6 },
    obstacles: [
      [3, 1],
      [3, 5],
      [3, 4],
      [4, 1],
      [1, 1],
      [2, 1],
      [3, 3],
      [1, 3],
      [1, 4],
      [1, 5],
      [6, 1],
      [6, 2],
      [6, 3],
      [6, 4],
    ],
    waters: [
      { pos: [4, 0], freezeIn: 3 },
      { pos: [0, 4], freezeIn: 5 },
      { pos: [6, 5], freezeIn: 7 },
    ],
    items: [
      { type: ItemType.SHOE_YELLOW, pos: [0, 0], layer: 3 },
      { type: ItemType.HAT_PURPLE, pos: [0, 0], layer: 2 },
      { type: ItemType.LAMP_ORANGE, pos: [0, 0], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [0, 2], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [7, 5], layer: 1 },
    ],
    targets: [
      { type: ItemType.LAMP_ORANGE, pos: [4, 5] },
      { type: ItemType.HAT_PURPLE, pos: [0, 5] },
      { type: ItemType.SHOE_YELLOW, pos: [4, 4] },
    ],
    maxSteps: 15,
  },

  // 第 17 关
  {
    level: 17,
    grid: { rows: 9, cols: 6 },
    obstacles: [
      [7, 1],
      [7, 0],
      [7, 2],
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 3],
      [1, 4],
      [1, 5],
      [6, 2],
      [5, 2],
      [3, 2],
      [2, 2],
      [2, 4],
      [3, 4],
      [5, 4],
      [6, 4],
      [7, 4],
      [4, 4],
    ],
    portals: [
      { id: 1, pos: [0, 5], uses: 1 },
      { id: 1, pos: [8, 0], uses: 1 },
      { id: 2, pos: [2, 0], uses: 1 },
      { id: 2, pos: [7, 5], uses: 1 },
    ],
    waters: [
      { pos: [8, 5], freezeIn: 5 },
      { pos: [2, 0], freezeIn: 1 },
    ],
    items: [
      { type: ItemType.APPLE_GREEN, pos: [0, 3], layer: 1 },
      { type: ItemType.HEADPHONE_BLACK, pos: [8, 3], layer: 1 },
      { type: ItemType.MUG_RED, pos: [4, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.APPLE_GREEN, pos: [8, 5] },
      { type: ItemType.HEADPHONE_BLACK, pos: [2, 3] },
      { type: ItemType.MUG_RED, pos: [2, 5] },
    ],
    maxSteps: 5,
  },

  // 第 18 关
  {
    level: 18,
    grid: { rows: 9, cols: 6 },
    obstacles: [
      [6, 1],
      [8, 1],
    ],
    items: [
      { type: ItemType.LAMP_ORANGE, pos: [0, 0], layer: 3 },
      { type: ItemType.HAT_PURPLE, pos: [2, 0], layer: 3 },
      { type: ItemType.HEADPHONE_BLACK, pos: [4, 0], layer: 3 },
      { type: ItemType.HEADPHONE_BLACK, pos: [0, 0], layer: 2 },
      { type: ItemType.LAMP_ORANGE, pos: [2, 0], layer: 2 },
      { type: ItemType.HAT_PURPLE, pos: [4, 0], layer: 2 },
      { type: ItemType.LAMP_ORANGE, pos: [4, 0], layer: 1 },
      { type: ItemType.HEADPHONE_BLACK, pos: [2, 0], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [0, 0], layer: 1 },
      { type: ItemType.MUG_RED, pos: [6, 5], layer: 3 },
      { type: ItemType.BOOK_BLUE, pos: [6, 5], layer: 2 },
      { type: ItemType.PLANT_GREEN, pos: [6, 5], layer: 1 },
      { type: ItemType.BOOK_BLUE, pos: [8, 5], layer: 3 },
      { type: ItemType.PLANT_GREEN, pos: [8, 5], layer: 2 },
      { type: ItemType.MUG_RED, pos: [8, 5], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [8, 2], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [8, 2], layer: 2 },
      { type: ItemType.HEADPHONE_BLACK, pos: [8, 2], layer: 3 },
      { type: ItemType.HEADPHONE_BLACK, pos: [7, 1], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [7, 1], layer: 2 },
      { type: ItemType.LAMP_ORANGE, pos: [7, 1], layer: 3 },
      { type: ItemType.PLANT_GREEN, pos: [6, 2], layer: 3 },
      { type: ItemType.MUG_RED, pos: [6, 2], layer: 2 },
      { type: ItemType.BOOK_BLUE, pos: [6, 2], layer: 1 },
    ],
    targets: [
      { type: ItemType.HAT_PURPLE, pos: [0, 4] },
      { type: ItemType.LAMP_ORANGE, pos: [2, 4] },
      { type: ItemType.MUG_RED, pos: [6, 0] },
      { type: ItemType.PLANT_GREEN, pos: [8, 0] },
      { type: ItemType.HEADPHONE_BLACK, pos: [7, 5] },
      { type: ItemType.BOOK_BLUE, pos: [4, 4] },
    ],
    maxSteps: 80,
  },

  // 第 19 关
  {
    level: 19,
    grid: { rows: 9, cols: 6 },
    obstacles: [
      [0, 4],
      [1, 4],
      [2, 4],
      [3, 4],
      [6, 4],
      [7, 4],
      [8, 4],
      [5, 2],
      [6, 3],
      [2, 0],
      [3, 3],
      [3, 2],
      [4, 2],
      [6, 2],
    ],
    portals: [
      { id: 1, pos: [0, 0], uses: 4 },
      { id: 1, pos: [5, 4], uses: 4 },
    ],
    waters: [
      { pos: [1, 5], freezeIn: 4 },
      { pos: [2, 1], freezeIn: 8 },
    ],
    items: [
      { type: ItemType.LAMP_ORANGE, pos: [0, 3], layer: 1 },
      { type: ItemType.HEADPHONE_BLACK, pos: [1, 0], layer: 2 },
      { type: ItemType.PLANT_GREEN, pos: [1, 0], layer: 1 },
      { type: ItemType.PLANT_GREEN, pos: [6, 0], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [7, 0], layer: 2 },
      { type: ItemType.SHOE_YELLOW, pos: [7, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.HEADPHONE_BLACK, pos: [4, 5] },
      { type: ItemType.LAMP_ORANGE, pos: [0, 5] },
      { type: ItemType.PLANT_GREEN, pos: [6, 5] },
      { type: ItemType.SHOE_YELLOW, pos: [7, 3] },
      { type: ItemType.HAT_PURPLE, pos: [0, 1] },
    ],
    maxSteps: 17,
  },

  // 第 20 关
  {
    level: 20,
    grid: { rows: 9, cols: 7 },
    obstacles: [
      [6, 4],
      [8, 4],
      [6, 2],
      [8, 2],
      [5, 2],
      [5, 4],
      [2, 2],
      [5, 3],
      [2, 4],
      [1, 3],
      [3, 3],
      [3, 2],
      [3, 4],
    ],
    oneways: [
      { pos: [4, 3], dir: 'right' },
      { pos: [7, 3], dir: 'left' },
      { pos: [0, 2], dir: 'right' },
      { pos: [0, 4], dir: 'right' },
    ],
    items: [
      { type: ItemType.HEADPHONE_BLACK, pos: [4, 6], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [7, 0], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [0, 3], layer: 1 },
    ],
    targets: [
      { type: ItemType.LAMP_ORANGE, pos: [7, 6] },
      { type: ItemType.HEADPHONE_BLACK, pos: [4, 0] },
      { type: ItemType.HAT_PURPLE, pos: [0, 0] },
    ],
    maxSteps: 20,
  },

  // 第 21 关
  {
    level: 21,
    grid: { rows: 9, cols: 7 },
    obstacles: [
      [0, 2],
      [0, 4],
      [1, 4],
      [6, 4],
      [8, 4],
      [6, 2],
      [8, 2],
      [5, 2],
      [5, 4],
      [2, 2],
      [4, 5],
      [3, 2],
      [5, 3],
      [3, 3],
    ],
    portals: [
      { id: 1, pos: [4, 4], uses: 2 },
      { id: 1, pos: [6, 3], uses: 2 },
    ],
    oneways: [
      { pos: [3, 4], dir: 'down' },
      { pos: [1, 2], dir: 'right' },
      { pos: [7, 5], dir: 'left' },
    ],
    items: [
      { type: ItemType.HEADPHONE_BLACK, pos: [4, 6], layer: 1 },
      { type: ItemType.APPLE_GREEN, pos: [0, 3], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [6, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.HEADPHONE_BLACK, pos: [3, 0] },
      { type: ItemType.LAMP_ORANGE, pos: [7, 6] },
      { type: ItemType.APPLE_GREEN, pos: [8, 3] },
    ],
    maxSteps: 15,
  },

  // 第 22 关
  {
    level: 22,
    grid: { rows: 9, cols: 8 },
    obstacles: [
      [4, 5],
      [6, 5],
      [1, 0],
      [1, 1],
      [1, 2],
      [1, 3],
      [1, 4],
      [7, 5],
      [3, 5],
    ],
    portals: [
      { id: 1, pos: [8, 0], uses: 5 },
      { id: 2, pos: [4, 0], uses: 3 },
      { id: 2, pos: [0, 2], uses: 3 },
      { id: 1, pos: [0, 7], uses: 5 },
    ],
    oneways: [
      { pos: [5, 5], dir: 'left' },
      { pos: [8, 5], dir: 'left' },
      { pos: [0, 5], dir: 'left' },
      { pos: [2, 5], dir: 'right' },
    ],
    items: [
      { type: ItemType.ALARM_PINK, pos: [6, 0], layer: 3 },
      { type: ItemType.HAT_PURPLE, pos: [0, 0], layer: 2 },
      { type: ItemType.LAMP_ORANGE, pos: [0, 0], layer: 1 },
      { type: ItemType.HEADPHONE_BLACK, pos: [6, 0], layer: 2 },
      { type: ItemType.SHOE_YELLOW, pos: [6, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.ALARM_PINK, pos: [6, 7] },
      { type: ItemType.HAT_PURPLE, pos: [4, 7] },
      { type: ItemType.HEADPHONE_BLACK, pos: [8, 7] },
      { type: ItemType.SHOE_YELLOW, pos: [0, 3] },
      { type: ItemType.LAMP_ORANGE, pos: [2, 0] },
    ],
    maxSteps: 18,
  },

  // 第 23 关
  {
    level: 23,
    grid: { rows: 9, cols: 8 },
    obstacles: [
      [8, 2],
      [8, 4],
      [0, 2],
      [0, 4],
      [3, 7],
      [5, 7],
      [2, 0],
      [4, 0],
    ],
    waters: [
      { pos: [7, 3], freezeIn: 5 },
      { pos: [1, 3], freezeIn: 3 },
      { pos: [4, 6], freezeIn: 2 },
      { pos: [3, 1], freezeIn: 1 },
    ],
    oneways: [
      { pos: [7, 3], dir: 'down' },
      { pos: [1, 3], dir: 'up' },
      { pos: [4, 6], dir: 'right' },
      { pos: [3, 1], dir: 'left' },
    ],
    items: [
      { type: ItemType.PLANT_GREEN, pos: [4, 5], layer: 1 },
      { type: ItemType.SHOE_YELLOW, pos: [3, 3], layer: 1 },
      { type: ItemType.BOOK_BLUE, pos: [4, 3], layer: 1 },
      { type: ItemType.MUG_RED, pos: [3, 4], layer: 1 },
    ],
    targets: [
      { type: ItemType.MUG_RED, pos: [8, 3] },
      { type: ItemType.PLANT_GREEN, pos: [4, 7] },
      { type: ItemType.BOOK_BLUE, pos: [0, 3] },
      { type: ItemType.SHOE_YELLOW, pos: [3, 0] },
    ],
    maxSteps: 5,
  },

  // 第 24 关
  {
    level: 24,
    grid: { rows: 9, cols: 6 },
    obstacles: [
      [3, 0],
      [5, 0],
      [7, 0],
      [1, 5],
      [3, 5],
      [5, 5],
    ],
    portals: [
      { id: 1, pos: [4, 0], uses: 3 },
      { id: 2, pos: [6, 0], uses: 3 },
      { id: 1, pos: [2, 5], uses: 3 },
      { id: 2, pos: [4, 5], uses: 3 },
    ],
    waters: [
      { pos: [4, 2], freezeIn: 5 },
    ],
    oneways: [
      { pos: [2, 1], dir: 'right' },
      { pos: [2, 2], dir: 'right' },
      { pos: [2, 3], dir: 'right' },
      { pos: [6, 3], dir: 'left' },
      { pos: [6, 2], dir: 'left' },
      { pos: [6, 1], dir: 'left' },
      { pos: [3, 2], dir: 'right' },
      { pos: [5, 2], dir: 'left' },
      { pos: [2, 4], dir: 'right' },
      { pos: [6, 4], dir: 'left' },
    ],
    items: [
      { type: ItemType.HAT_PURPLE, pos: [0, 0], layer: 3 },
      { type: ItemType.LAMP_ORANGE, pos: [0, 0], layer: 2 },
      { type: ItemType.ALARM_PINK, pos: [0, 0], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [8, 5], layer: 1 },
      { type: ItemType.ALARM_PINK, pos: [8, 5], layer: 2 },
      { type: ItemType.HAT_PURPLE, pos: [8, 5], layer: 3 },
    ],
    targets: [
      { type: ItemType.HAT_PURPLE, pos: [3, 3] },
      { type: ItemType.ALARM_PINK, pos: [5, 3] },
      { type: ItemType.LAMP_ORANGE, pos: [3, 1] },
    ],
    maxSteps: 25,
  },

  // 第 25 关
  {
    level: 25,
    grid: { rows: 9, cols: 6 },
    obstacles: [
      [2, 0],
      [0, 0],
      [2, 3],
      [3, 5],
      [2, 4],
      [4, 4],
      [4, 3],
      [5, 4],
      [6, 5],
      [7, 4],
      [5, 2],
      [5, 1],
      [5, 0],
      [6, 0],
      [7, 0],
      [7, 1],
      [7, 2],
      [8, 3],
    ],
    portals: [
      { id: 2, pos: [1, 0], uses: 3 },
      { id: 2, pos: [6, 4], uses: 3 },
      { id: 1, pos: [3, 4], uses: 2 },
      { id: 1, pos: [6, 1], uses: 2 },
    ],
    waters: [
      { pos: [3, 2], freezeIn: 3 },
      { pos: [1, 3], freezeIn: 4 },
    ],
    oneways: [
      { pos: [1, 1], dir: 'left' },
    ],
    items: [
      { type: ItemType.MUG_RED, pos: [1, 5], layer: 3 },
      { type: ItemType.HEADPHONE_BLACK, pos: [1, 5], layer: 2 },
      { type: ItemType.APPLE_GREEN, pos: [1, 5], layer: 1 },
      { type: ItemType.MUG_RED, pos: [3, 0], layer: 1 },
    ],
    targets: [
      { type: ItemType.MUG_RED, pos: [3, 3] },
      { type: ItemType.HEADPHONE_BLACK, pos: [5, 3] },
      { type: ItemType.APPLE_GREEN, pos: [7, 3] },
    ],
    maxSteps: 8,
  },

  // 第 26 关
  {
    level: 26,
    grid: { rows: 9, cols: 7 },
    obstacles: [],
    items: [
      { type: ItemType.BOOK_BLUE, pos: [2, 1], layer: 3 },
      { type: ItemType.BOOK_BLUE, pos: [4, 5], layer: 3 },
      { type: ItemType.BOOK_BLUE, pos: [6, 1], layer: 3 },
      { type: ItemType.BOOK_BLUE, pos: [6, 5], layer: 3 },
      { type: ItemType.PLANT_GREEN, pos: [4, 1], layer: 3 },
      { type: ItemType.PLANT_GREEN, pos: [2, 5], layer: 3 },
      { type: ItemType.PLANT_GREEN, pos: [7, 3], layer: 3 },
      { type: ItemType.PLANT_GREEN, pos: [1, 3], layer: 3 },
      { type: ItemType.ALARM_PINK, pos: [6, 1], layer: 2 },
      { type: ItemType.ALARM_PINK, pos: [2, 5], layer: 2 },
      { type: ItemType.BOOK_BLUE, pos: [2, 1], layer: 2 },
      { type: ItemType.MUG_RED, pos: [4, 5], layer: 2 },
      { type: ItemType.MUG_RED, pos: [1, 3], layer: 2 },
      { type: ItemType.SHOE_YELLOW, pos: [6, 5], layer: 2 },
      { type: ItemType.HAT_PURPLE, pos: [4, 1], layer: 2 },
      { type: ItemType.HAT_PURPLE, pos: [7, 3], layer: 2 },
      { type: ItemType.HEADPHONE_BLACK, pos: [2, 1], layer: 1 },
      { type: ItemType.HEADPHONE_BLACK, pos: [4, 5], layer: 1 },
      { type: ItemType.HEADPHONE_BLACK, pos: [6, 1], layer: 1 },
      { type: ItemType.SHOE_YELLOW, pos: [2, 5], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [6, 5], layer: 1 },
      { type: ItemType.LAMP_ORANGE, pos: [1, 3], layer: 1 },
      { type: ItemType.ALARM_PINK, pos: [7, 3], layer: 1 },
      { type: ItemType.BOOK_BLUE, pos: [4, 1], layer: 1 },
    ],
    targets: [
      { type: ItemType.MUG_RED, pos: [2, 1] },
      { type: ItemType.BOOK_BLUE, pos: [4, 1] },
      { type: ItemType.PLANT_GREEN, pos: [6, 1] },
      { type: ItemType.SHOE_YELLOW, pos: [2, 5] },
      { type: ItemType.HAT_PURPLE, pos: [4, 5] },
      { type: ItemType.LAMP_ORANGE, pos: [6, 5] },
      { type: ItemType.HEADPHONE_BLACK, pos: [1, 3] },
      { type: ItemType.ALARM_PINK, pos: [7, 3] },
    ],
  },

  // 第 27 关
  {
    level: 27,
    grid: { rows: 9, cols: 7 },
    obstacles: [],
    waters: [
      { pos: [4, 2], freezeIn: 1 },
      { pos: [5, 3], freezeIn: 2 },
      { pos: [4, 4], freezeIn: 3 },
      { pos: [3, 3], freezeIn: 4 },
      { pos: [4, 3], freezeIn: 5 },
    ],
    oneways: [
      { pos: [5, 1], dir: 'down' },
      { pos: [3, 5], dir: 'up' },
    ],
    items: [
      { type: ItemType.SHOE_YELLOW, pos: [0, 3], layer: 3 },
      { type: ItemType.HAT_PURPLE, pos: [0, 6], layer: 3 },
      { type: ItemType.APPLE_GREEN, pos: [4, 0], layer: 3 },
      { type: ItemType.HEADPHONE_BLACK, pos: [3, 6], layer: 3 },
      { type: ItemType.SHOE_YELLOW, pos: [3, 6], layer: 2 },
      { type: ItemType.HAT_PURPLE, pos: [4, 0], layer: 2 },
      { type: ItemType.BOOK_BLUE, pos: [0, 6], layer: 2 },
      { type: ItemType.HEADPHONE_BLACK, pos: [0, 3], layer: 2 },
      { type: ItemType.APPLE_GREEN, pos: [4, 0], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [0, 3], layer: 1 },
      { type: ItemType.BOOK_BLUE, pos: [3, 6], layer: 1 },
      { type: ItemType.SHOE_YELLOW, pos: [0, 6], layer: 1 },
      { type: ItemType.HAT_PURPLE, pos: [8, 6], layer: 1 },
      { type: ItemType.HEADPHONE_BLACK, pos: [8, 6], layer: 2 },
      { type: ItemType.BOOK_BLUE, pos: [8, 6], layer: 3 },
      { type: ItemType.PLANT_GREEN, pos: [5, 6], layer: 3 },
      { type: ItemType.BOOK_BLUE, pos: [5, 6], layer: 2 },
      { type: ItemType.HEADPHONE_BLACK, pos: [5, 6], layer: 1 },
    ],
    targets: [
      { type: ItemType.APPLE_GREEN, pos: [4, 6] },
      { type: ItemType.HEADPHONE_BLACK, pos: [3, 0] },
      { type: ItemType.BOOK_BLUE, pos: [0, 0] },
      { type: ItemType.HAT_PURPLE, pos: [8, 0] },
      { type: ItemType.SHOE_YELLOW, pos: [8, 3] },
      { type: ItemType.PLANT_GREEN, pos: [5, 0] },
    ],
  },

  // 第 28 关
  {
    level: 28,
    grid: { rows: 5, cols: 5 },
    obstacles: [],
    buttons: [
      { id: 1, pos: [0, 0] },
    ],
    activeBarriers: [
      { id: 1, pos: [2, 2], kind: 'wall' },
    ],
    items: [
      { type: ItemType.MUG_RED, pos: [4, 0], layer: 1 },
      { type: ItemType.BOOK_BLUE, pos: [2, 0], layer: 1 },
      { type: ItemType.PLANT_GREEN, pos: [2, 4], layer: 1 },
    ],
    targets: [
      { type: ItemType.MUG_RED, pos: [0, 4] },
      { type: ItemType.BOOK_BLUE, pos: [4, 4] },
      { type: ItemType.PLANT_GREEN, pos: [0, 2] },
    ],
  }
];

/**
 * 根据关卡编号获取关卡配置
 * @param level 关卡编号（从 1 开始）
 * @returns 关卡配置，如果不存在返回 null
 */
export function getLevelConfig(level: number): LevelConfig | null {
  if (level < 1 || level > LEVELS.length) return null;
  return LEVELS[level - 1];
}

/** 总关卡数 */
export const TOTAL_LEVELS = LEVELS.length;
